backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Lead1", name: "lead1", widget: "string"}
        - { label: "Lead2", name: "lead2", widget: "string"}
        - { label: "Availability Date", name: "availabilityDate", widget: "date" }
        - { label: "Body", name: "body", widget: "markdown"}
    - label: "Skillset"
      name: "skillset"
      file: "content/skillset.md"
      fields:
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Front end'
          name: "frontEnd"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "text"}
        - label: 'Back end'
          name: "backEnd"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "text"}
        - label: 'Dev Ops'
          name: "devops"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "text"}
        - label: 'Process'
          name: "process"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "text"}
    - label: "Projects"
      name: "projects"
      file: "content/projects.md"
      fields:
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Projects'
          name: "projects"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "text"}
            - { label: "Organisation", name: "organisation", widget: "text"}
            - { label: "Sector", name: "sector", widget: "text"}
            - { label: "City", name: "city", widget: "text"}
            - { label: "Based", name: "based", widget: "select", options: ["R", "S", "H"]}
            - { label: "Contract Type", name: "contractType", widget: "select", options: ["C", "F", "P"]}
            - { label: "Renewals", name: "renewals", widget: "number"}
            - { label: "Duration (months)", name: "duration", widget: "number"}
            - { label: "Start", name: "start", widget: "date"}
            - { label: "End", name: "end", widget: "date"}
            - { label: "Stack Type", name: "stackType", widget: "select", options: ["Front End", "Back End", "Full Stack"]}
            - { label: "Synopsis", name: "synopsis", widget: "text"}
            - { label: "Skills", name: "skills", widget: "select", multiple: true, options: ["React", "TypeScript", "JavaScript", "Material Design", "JSS", "Cypress", "ASP.Net Core", "C#", "SQL Server", "RethinkDB", "Angular", "Web API"]}
    - label: "Testimonials"
      name: "testimonials"
      file: "content/testimonials.md"
      fields:
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Testimonials'
          name: "testimonials"
          widget: list
          fields:
            - { label: "From", name: "from", widget: "text"}
            - { label: "Quote", name: "quote", widget: "text"}
            - { label: "Client", name: "client", widget: "string"}
