backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Availability Date", name: "availabilityDate", widget: "date" }
        - { label: "Body", name: "body", widget: "markdown"}
    - label: "Skills"
      name: "skills"
      file: "content/skills.md"
      fields:
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Core Skills'
          name: "coreSkills"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "text"}
    - label: "CV"
      name: "cv"
      file: "content/cv.md"
      fields:
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Assignments'
          name: "assignments"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "text"}
            - { label: "Organisation", name: "organisation", widget: "text"}
            - { label: "Start", name: "start", widget: "date"}
            - { label: "End", name: "end", widget: "date"}
    - label: "Recommendations"
      name: "recommendations"
      file: "content/recommendations.md"
      fields:
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Recommendations'
          name: "recommendations"
          widget: list
          fields:
            - { label: "From", name: "from", widget: "text"}
            - { label: "Quote", name: "quote", widget: "text"}
            - { label: "Client", name: "client", widget: "string"}
